name: FFMPEG_ACTION

on:
  workflow_dispatch:
  # Run 6 Hours after https://github.com/bitsbb01/iptvcat-scrapper
  # 12.10 UTC Time, 06.10 Central Time
  # Changed to every 3hrs, due to including Youtube links, so those links are always correct.
  schedule:
    - cron: "0 0/3 * * *"
  push:
    branches:
    - master
    - main

jobs:

  ffmpegaction:
    name: FFMPEG_Creator
    runs-on: "ubuntu-latest"

    steps:
     - uses: actions/checkout@v2
     - name: ffmepg
       uses: FedericoCarboni/setup-ffmpeg@v1
       with:
      # Not strictly necessary, but it may prevent rate limit
      # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
       id: setup-ffmpeg
     - run: ffmpeg -i https://stream-cdn.vaughnsoft.net/play/live_rickstunes.flv output.mp4
     
     - name: push
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.scrapper_token }}
         branch: ${{ github.ref }} 
  
     - name: comit
       uses: zwaldowski/git-commit-action@v1
       with:
             commit_message: Updated by Bot - ${{ steps.date.outputs.date }}
             working_directory: .

     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.scrapper_token }}
          branch: ${{ github.ref }}
          
